/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buttonOnTable;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ASUS
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
    }
    
    public void initEvent(TableActionEvent event, int row) {
        hapus.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed (ActionEvent ae){
                event.onDelete(row);
        }
                
    });
        edit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed (ActionEvent ae){
                event.onEdit(row);
                }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        hapus = new com.buttonOnTable.ActionButton();
        edit = new com.buttonOnTable.ActionButton();

        setLayout(new java.awt.GridBagLayout());

        hapus.setBackground(new java.awt.Color(255, 153, 204));
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/picture/hapus (1) (2).png"))); // NOI18N
        hapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -4;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        add(hapus, gridBagConstraints);

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/picture/edit.png"))); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(edit, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.buttonOnTable.ActionButton edit;
    private com.buttonOnTable.ActionButton hapus;
    // End of variables declaration//GEN-END:variables
}
