/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import com.buttonOnTable.TableActionCellEditor;
import com.buttonOnTable.TableActionCellRenderer;
import com.buttonOnTable.TableActionEvent;
import com.panel.belanja;
import static com.panel.belanja.table_belanja;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.konek;

/**
 *
 * @author ASUS
 */
public class editBelanja extends javax.swing.JFrame {

    /**
     * Creates new form editBelanja
     */
    public editBelanja() {
        initComponents();
        getContentPane().setBackground(new Color(240, 240, 240));
        dateChooser2.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser2.hidePopup();
                }} 
        });
    }
    
    public void data_table() { 
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Kode Belanja");
            tbl.addColumn("Tanggal");
            tbl.addColumn("Uang Belanja");
            tbl.addColumn("Keterangan");
            tbl.addColumn("Action");
            belanja.table_belanja.setModel(tbl);
            
        try{
            Statement statement = (Statement)konek.GetConnection().createStatement();
            ResultSet res= statement.executeQuery("select * from belanja");
        while (res.next()) {
            tbl.addRow(new Object[] {
                res.getString("kode_belanja"),
                res.getDate("tanggal"),
                res.getInt("total"),
                res.getString("keterangan")
            });
         belanja.table_belanja.setModel(tbl);
        }
      }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "salah"); 
      }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser2 = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        background2 = new com.swing.background();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        shape51 = new com.swing.Shape5();
        txt_editkode = new javax.swing.JTextField();
        shape52 = new com.swing.Shape5();
        txt_edittanggal = new javax.swing.JTextField();
        shape53 = new com.swing.Shape5();
        txt_edituang = new javax.swing.JTextField();
        shape54 = new com.swing.Shape5();
        txt_editketerangan = new javax.swing.JTextField();
        background1 = new com.swing.background();
        shape1 = new com.swing.Shape();
        background3 = new com.swing.background();
        jLabel5 = new javax.swing.JLabel();

        dateChooser2.setForeground(new java.awt.Color(0, 167, 157));
        dateChooser2.setDateFormat("yyyy-MM-dd");
        dateChooser2.setTextRefernce(txt_edittanggal);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background2.setBackground(new java.awt.Color(255, 255, 255));
        background2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Keterangan");
        background2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Kode Belanja");
        background2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tanggal");
        background2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Uang Belanja");
        background2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        simpan.setBackground(new java.awt.Color(0, 167, 157));
        simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/picture/simpan (2).png"))); // NOI18N
        simpan.setText("Simpan");
        simpan.setBorder(null);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        background2.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 100, 40));

        batal.setBackground(new java.awt.Color(0, 167, 157));
        batal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/picture/close_1.png"))); // NOI18N
        batal.setText("Batal");
        batal.setBorder(null);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        background2.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 98, 41));

        javax.swing.GroupLayout shape51Layout = new javax.swing.GroupLayout(shape51);
        shape51.setLayout(shape51Layout);
        shape51Layout.setHorizontalGroup(
            shape51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        shape51Layout.setVerticalGroup(
            shape51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        background2.add(shape51, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, 30));

        txt_editkode.setBackground(new java.awt.Color(122, 178, 178));
        txt_editkode.setBorder(null);
        txt_editkode.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_editkode.setEnabled(false);
        background2.add(txt_editkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, 28));

        javax.swing.GroupLayout shape52Layout = new javax.swing.GroupLayout(shape52);
        shape52.setLayout(shape52Layout);
        shape52Layout.setHorizontalGroup(
            shape52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        shape52Layout.setVerticalGroup(
            shape52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        background2.add(shape52, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 220, 30));

        txt_edittanggal.setBackground(new java.awt.Color(122, 178, 178));
        txt_edittanggal.setBorder(null);
        txt_edittanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edittanggalActionPerformed(evt);
            }
        });
        background2.add(txt_edittanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        javax.swing.GroupLayout shape53Layout = new javax.swing.GroupLayout(shape53);
        shape53.setLayout(shape53Layout);
        shape53Layout.setHorizontalGroup(
            shape53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        shape53Layout.setVerticalGroup(
            shape53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        background2.add(shape53, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, 30));

        txt_edituang.setBackground(new java.awt.Color(122, 178, 178));
        txt_edituang.setBorder(null);
        background2.add(txt_edituang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 200, 30));

        javax.swing.GroupLayout shape54Layout = new javax.swing.GroupLayout(shape54);
        shape54.setLayout(shape54Layout);
        shape54Layout.setHorizontalGroup(
            shape54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        shape54Layout.setVerticalGroup(
            shape54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        background2.add(shape54, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 220, 70));

        txt_editketerangan.setBackground(new java.awt.Color(122, 178, 178));
        txt_editketerangan.setBorder(null);
        txt_editketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_editketeranganActionPerformed(evt);
            }
        });
        background2.add(txt_editketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, 66));

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        background2.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 310, 60));

        shape1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Edit Belanja");

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        shape1.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 380));

        background2.add(shape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 400));

        jPanel1.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_editketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_editketeranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_editketeranganActionPerformed

    private void txt_edittanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edittanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edittanggalActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_batalActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String tanggal = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tanggal);

        String kode_belanja = txt_editkode.getText();
        String tanggal1 = txt_edittanggal.getText();
        String uang_belanja = txt_edituang.getText();
        String keterangan = txt_editketerangan.getText();
        try {
            Statement st = konek.GetConnection().createStatement();
            st.executeUpdate("UPDATE belanja SET tanggal='" + tanggal1 + "', total= '" + uang_belanja +
                "',  keterangan= '" + keterangan + "' WHERE kode_belanja='" + kode_belanja + "';");

            JOptionPane.showMessageDialog(null, " Berhasil Diubah");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " Gagal Diubah");
        }
        dispose();
        data_table();
        setTableAction();
    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editBelanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editBelanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editBelanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editBelanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editBelanja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.swing.background background1;
    private com.swing.background background2;
    private com.swing.background background3;
    private javax.swing.JButton batal;
    private com.raven.datechooser.DateChooser dateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private com.swing.Shape shape1;
    public com.swing.Shape5 shape51;
    public com.swing.Shape5 shape52;
    public com.swing.Shape5 shape53;
    public com.swing.Shape5 shape54;
    private javax.swing.JButton simpan;
    public javax.swing.JTextField txt_editketerangan;
    public javax.swing.JTextField txt_editkode;
    public javax.swing.JTextField txt_edittanggal;
    public javax.swing.JTextField txt_edituang;
    // End of variables declaration//GEN-END:variables

    private void setTableAction() {
        TableActionEvent event = new TableActionEvent(){
    
            @Override
            public void onDelete(int row) { 
            }

           @Override
            public void onEdit(int row) {
            
    }
        };
        table_belanja.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRenderer());
        table_belanja.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditor(event));
                }
}

       
        
        

